# This is a basic workflow to help you get started with Actions

name: build-macos

# Controls when the workflow will run
on:
  # this is a called workflow
  workflow_call:
    outputs:
      build-file:
        description: "The output of this build procsss"
        value: ${{ jobs.macos-build-job.outputs.install-file }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer on mac
  macos-build-job:
    # The type of runner that the job will run on
    runs-on: macos-13
    
    # Output
    outputs:
      install-file: ${{ steps.output-installer.outputs.filename }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Setup python
      - name: System Setup
        run: |
          pip install pyinstaller Pillow pyqt5 darkdetect argparse intelhex esptool mpremote requests psutil
          brew install create-dmg

      # Build the installer.
      - name: Build Mac Installer
        run: |
          sudo mv MicroPython_Firmware_Uploader/resource/teensy_loader_cli_mac MicroPython_Firmware_Uploader/resource/teensy_loader_cli.exe
          sudo chmod +x MicroPython_Firmware_Uploader/resource/teensy_loader_cli.exe
          ESPTOOL_LOCATION=$(pip show esptool | grep "Location: " | cut -c 11- | tr -d '\n')
          ESPTOOL_TARGETS_1=$(echo "${ESPTOOL_LOCATION}/esptool/targets/stub_flasher/1/*.json:./esptool/targets/stub_flasher/1/")
          ESPTOOL_TARGETS_2=$(echo "${ESPTOOL_LOCATION}/esptool/targets/stub_flasher/2/*.json:./esptool/targets/stub_flasher/2/")
          pyinstaller --windowed -n MicroPythonUploader --noconsole --distpath=. --icon=MicroPython_Firmware_Uploader/resource/sfe_flame.ico --add-data="MicroPython_Firmware_Uploader/resource/*:resource/" --add-data="${ESPTOOL_TARGETS_1}" --add-data="${ESPTOOL_TARGETS_2}" MicroPython_Firmware_Upload.py
          mkdir tmp
          mv "MicroPythonUploader.app" "tmp/"
          create-dmg --volicon "MicroPython_Firmware_Uploader/resource/sparkdisk.icns" --background "MicroPython_Firmware_Uploader/resource/sfe_logo_med.png" --hide-extension "MicroPythonUploader.app" --icon "MicroPythonUploader.app" 100 100 --window-size 600 440 --app-drop-link 400 100 "MicroPythonUploader.dmg" "tmp/"
          
      - uses: actions/upload-artifact@v4
        with:
          name: MicroPythonUploader.dmg
          path: MicroPythonUploader.dmg

      - id: output-installer
        run: echo "filename=MicroPythonUploader.dmg" >> $GITHUB_OUTPUT
        
        
